/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Смоук-проверка после деплоя */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация (email + пароль) */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход, выдача access + refresh */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновить access по refresh-токену */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список моих Разборов (кабинет) */
        get: operations["listReviews"];
        put?: never;
        /**
         * Загрузить Деку (+ опц. Запись питча, Excel) и запустить Разбор
         * @description Атомарно списывает один Разбор: сначала из пробных (free_reviews_left),
         *     затем из купленных (balance_reviews). Когда оба счётчика пусты — 402
         *     LIMIT_REACHED с предложением пополнить баланс; на платном плане это тоже
         *     действует, безлимита нет. Если Разбор завершится статусом failed, Разбор
         *     возвращается в тот же счётчик, из которого был списан. Ретрая нет —
         *     повтор = новая загрузка.
         */
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Статус Разбора (фронт поллит каждые 5 с) */
        get: operations["getReview"];
        put?: never;
        post?: never;
        /**
         * Удалить Дeку целиком — Разбор, файлы, Находки и все попытки репетиции
         * @description Каскадно удаляет всё, что ссылается на этот Разбор (Находки, файлы, попытки
         *     репетиции с их аудиозаписями), включая сами файлы на диске, не только строки в БД.
         *     Бесплатный кредит не возвращается.
         */
        delete: operations["deleteReview"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Готовый Отчёт (только при status=done) */
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{id}/slides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Все рендеренные слайды Деки (для режима репетиции)
         * @description В отличие от Находок (скриншот только у слайдов с bbox-Находкой, ADR 0002),
         *     отдаёт PNG каждого слайда — нужно листать Деку во время записи репетиции.
         *     Лениво досчитывается из сохранённого оригинала при первом обращении к Разбору.
         */
        get: operations["getSlides"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{id}/rehearsals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Попытки репетиции для этого Разбора (для графика прогресса, П4) */
        get: operations["listRehearsals"];
        put?: never;
        /**
         * Загрузить запись репетиции (аудио + тайминг слайдов) и запустить анализ
         * @description Разбор должен быть status=done (нужны текст слайдов и Дека для сверки).
         *     attempt_num вычисляется автоматически (+1 к последней попытке).
         */
        post: operations["createRehearsal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rehearsals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Статус попытки репетиции (фронт поллит до done/failed) */
        get: operations["getRehearsal"];
        put?: never;
        post?: never;
        /** Удалить попытку репетиции (запись + отчёт) */
        delete: operations["deleteRehearsal"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rehearsals/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Отчёт репетиции — карта тайминга, болота/заглушки, Находки, дельта (П3-П4) */
        get: operations["getRehearsalReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rehearsals/{id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Скачать исходную запись репетиции (доступна в любом статусе, включая failed) */
        get: operations["getRehearsalAudio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/{id}/flag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Пометить Находку как мусорную (👎 → user_flag + Langfuse)
         * @description Взаимоисключающе с `/like`: при 👎 сбрасывается `user_like`.
         */
        post: operations["flagFinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/{id}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Пометить Находку как полезную (👍 → user_like + Langfuse)
         * @description Взаимоисключающе с `/flag`: при 👍 сбрасывается `user_flag`.
         */
        post: operations["likeFinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/{id}/apply_fix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Точечно применить автофикс Находки к Исправленной деке
         * @description Только для `auto_fixable=true`. Перегенерирует `fixed.pptx` из оригинала
         *     по текущему набору применённых Находок (+ эта). Идемпотентно.
         *     Не-`auto_fixable` / чужая → `404`.
         */
        post: operations["applyFindingFix"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Отдача файла (PDF/fixed.pptx/скриншот) с проверкой владельца
         * @description Скриншоты в <img> не шлют заголовок Authorization, поэтому для них выдаётся
         *     короткоживущий signed-токен в query (?sig=...). Прочие файлы — по bearer.
         */
        get: operations["getFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Фронтовые события продуктовой аналитики (батчем) */
        post: operations["trackEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example Исчерпан лимит бесплатных разборов */
            detail: string;
            /** @example LIMIT_REACHED */
            code?: string | null;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthTokens: {
            access_token: string;
            refresh_token: string;
            /** @example bearer */
            token_type?: string;
            user: components["schemas"]["User"];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            plan: "free" | "paid";
            /**
             * @description Пробные Разборы. Тратятся раньше купленных.
             * @example 2
             */
            free_reviews_left: number;
            /**
             * @description Купленные Разборы (предоплаченный пакет). Списываются после того, как исчерпаны пробные; когда оба счётчика на нуле, createReview отвечает 402.
             * @default 0
             * @example 10
             */
            balance_reviews: number;
            email_verified: boolean;
            /**
             * @description Администратор — не тариф (plan остаётся free/paid), а флаг по email из ADMIN_EMAILS. Всегда обходит оба счётчика Разборов (см. LimitService).
             * @default false
             */
            is_admin: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        /** @enum {string} */
        ReviewStatus: "queued" | "processing" | "done" | "failed";
        ReviewOut: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["ReviewStatus"];
            /** @description Заполнен при status=done */
            score?: number | null;
            /** @description Человекочитаемая причина при status=failed */
            fail_reason?: string | null;
            /** @example q3-review.pptx */
            deck_filename: string;
            n_slides?: number | null;
            has_audio: boolean;
            has_data: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at?: string | null;
        };
        /** @enum {string} */
        Category: "TYPOGRAPHY" | "HIERARCHY" | "READABILITY" | "CONSISTENCY" | "CHART" | "NARRATIVE" | "SPEECH_MISMATCH" | "DELIVERY";
        /** @enum {string} */
        Severity: "CRITICAL" | "MAJOR" | "MINOR";
        /** @description Нормированные координаты 0..1 (не зависят от dpi) */
        BBox: {
            x: number;
            y: number;
            w: number;
            h: number;
        };
        Finding: {
            /** Format: uuid */
            id: string;
            /** @description null = Находка уровня Деки */
            slide_num?: number | null;
            category: components["schemas"]["Category"];
            severity: components["schemas"]["Severity"];
            title: string;
            description: string;
            fix_suggestion: string;
            bbox?: components["schemas"]["BBox"] | null;
            /**
             * Format: uuid
             * @description Аннотированный PNG (через GET /files/{asset_id})
             */
            screenshot_asset_id?: string | null;
            /**
             * @description Готовая ссылка `/files/{screenshot_asset_id}?sig=...` с коротким подписанным
             *     токеном (см. GET /files/{asset_id}), подписанная заново при каждой отдаче
             *     Отчёта — для прямой вставки в <img src>, без отдельного запроса за подписью.
             */
            screenshot_url?: string | null;
            auto_fixable: boolean;
            auto_fixed?: boolean;
            /** @description Имя анализатора */
            source?: string;
            /** @description Помечена 👎 */
            user_flag?: boolean;
            /** @description Помечена 👍 */
            user_like?: boolean;
        };
        /** @description Метрики Подачи (только если приложена Запись питча) */
        DeliveryMetrics: {
            words_per_minute?: number;
            /**
             * @example {
             *       "ээ": 12,
             *       "как бы": 5
             *     }
             */
            filler_words?: {
                [key: string]: number;
            };
            /** @description Таймкоды пауз > 3 с */
            long_pauses?: number[];
        };
        ReportOut: {
            /** Format: uuid */
            review_id: string;
            score: number;
            n_slides: number;
            findings: components["schemas"]["Finding"][];
            delivery?: components["schemas"]["DeliveryMetrics"] | null;
            auto_fixed_count: number;
            /** Format: uuid */
            pdf_asset_id?: string | null;
            /** Format: uuid */
            fixed_pptx_asset_id?: string | null;
            /**
             * @description Публичное имя файла для скачивания: `{имя Деки}_исправленная_версия№{N}.pptx`,
             *     N растёт при каждой перегенерации (см. POST /findings/{id}/apply_fix).
             */
            fixed_pptx_filename?: string | null;
        };
        SlideOut: {
            slide_num: number;
            /** @description Подписанная ссылка /files/{asset_id}?sig=... */
            url: string;
        };
        /** @enum {string} */
        RehearsalStatus: "queued" | "processing" | "done" | "failed";
        /** @description Один слайд — (start, end) в секундах от начала записи (точный тайминг, П2) */
        SlideTimingIn: {
            slide_num: number;
            start: number;
            end: number;
        };
        RehearsalOut: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            review_id: string;
            status: components["schemas"]["RehearsalStatus"];
            /** @description Человекочитаемая причина при status=failed */
            fail_reason?: string | null;
            /** @description Номер попытки для этого Разбора (1, 2, 3…) — для графика прогресса (П4) */
            attempt_num: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at?: string | null;
        };
        /** @description Карта тайминга по слайдам (П3) — фактически проведённое на слайде время */
        TimingMapEntry: {
            slide_num: number;
            start: number;
            end: number;
            duration: number;
            /**
             * @description swamp = «болото» (> 2 мин), stub = «заглушка» (< 5 с)
             * @enum {string|null}
             */
            pacing?: "swamp" | "stub" | null;
        };
        /** @description Находка репетиции (pacing/SPEECH_MISMATCH) — не связана с FindingRow Разбора */
        RehearsalFinding: {
            /** Format: uuid */
            id: string;
            slide_num?: number | null;
            category: components["schemas"]["Category"];
            severity: components["schemas"]["Severity"];
            title: string;
            description: string;
            fix_suggestion: string;
        };
        /** @description Дельта метрик Подачи к предыдущей done-попытке этого Разбора (П4) */
        RehearsalDelta: {
            previous_attempt_num: number;
            words_per_minute_delta: number;
            filler_words_delta: number;
            long_pauses_delta: number;
        };
        RehearsalReportOut: {
            /** Format: uuid */
            rehearsal_id: string;
            /** Format: uuid */
            review_id: string;
            attempt_num: number;
            status: components["schemas"]["RehearsalStatus"];
            fail_reason?: string | null;
            delivery?: components["schemas"]["DeliveryMetrics"] | null;
            timing_map: components["schemas"]["TimingMapEntry"][];
            findings: components["schemas"]["RehearsalFinding"][];
            delta?: components["schemas"]["RehearsalDelta"] | null;
        };
        EventIn: {
            /** @example report_opened */
            name: string;
            properties?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Нет/невалидный/протухший токен */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Не найдено или не принадлежит пользователю (US-8) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Конфликт (например, email занят) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Ошибка валидации тела запроса */
        Validation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ReviewId: string;
        RehearsalId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сервис жив */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Аккаунт создан (plan=free, free_reviews_left=2); сразу выдаются токены */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Токены выданы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description Новый access */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Профиль */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listReviews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Разборы текущего пользователя, новые сверху */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description PPTX/PDF, ≤ 50 МБ, ≤ 60 слайдов
                     */
                    deck: string;
                    /**
                     * Format: binary
                     * @description Опц. запись питча (mp4/mov/mp3/m4a/wav)
                     */
                    audio?: string;
                    /**
                     * Format: binary
                     * @description Опц. Excel с данными (.xlsx)
                     */
                    data?: string;
                };
            };
        };
        responses: {
            /** @description Разбор принят в очередь (status=queued) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Исчерпан лимит бесплатных Разборов */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Файл больше 50 МБ */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Validation"];
        };
    };
    getReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Текущее состояние Разбора */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалено */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Вью-модель Отчёта */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Разбор ещё не готов (status ≠ done) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSlides: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Слайды по порядку */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideOut"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Разбор ещё не готов (status ≠ done) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRehearsals: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Попытки по возрастанию attempt_num */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RehearsalOut"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createRehearsal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Запись с MediaRecorder (webm/ogg/mp4/mov/mp3/m4a/wav)
                     */
                    audio: string;
                    /** @description JSON-строка — массив SlideTimingIn */
                    slide_timings: string;
                };
            };
        };
        responses: {
            /** @description Репетиция принята в очередь (status=queued) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RehearsalOut"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Разбор ещё не готов (status ≠ done) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Validation"];
        };
    };
    getRehearsal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RehearsalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Текущее состояние попытки */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RehearsalOut"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteRehearsal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RehearsalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалена */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getRehearsalReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RehearsalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Вью-модель отчёта репетиции */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RehearsalReportOut"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Попытка ещё обрабатывается (status ≠ done) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRehearsalAudio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RehearsalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Бинарная аудио/видеозапись */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    flagFinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Отмечено */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    likeFinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Отмечено */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    applyFindingFix: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Фикс применён (или уже был применён) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getFile: {
        parameters: {
            query?: {
                /** @description Signed-токен для доступа из тега <img> */
                sig?: string;
            };
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Бинарный файл */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    trackEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventIn"][];
            };
        };
        responses: {
            /** @description Приняты */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
